name: Send video-feedback email

on:
  workflow_dispatch:
    inputs:
      feedback1:
        description: Preferred video for pair 1
        required: true
        type: string
      feedback2:
        description: Preferred video for pair 2
        required: true
        type: string
      feedback3:
        description: Preferred video for pair 3
        required: true
        type: string

jobs:
  email:
    runs-on: ubuntu-latest

    steps:
      - name: Send feedback mail
        uses: dawidd6/action-send-mail@v6   # marketplace action :contentReference[oaicite:0]{index=0}
        with:
          server_address: smtp.gmail.com    # or smtp.office365.com, etc.
          server_port: 465                 # 465 = SSL/TLS (use 587 + secure:false for STARTTLS)
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}   # e.g. mybot@gmail.com
          password: ${{ secrets.MAIL_PASSWORD }}   # app-specific password
          subject: "New TacTGen video feedback"
          to:     "820144073@qq.com"
          from:   "TacTGen Bot <${{ secrets.MAIL_USERNAME }}>"
          body: |
            A visitor has submitted video-comparison feedback:

            • Pair 1 ⇒ ${{ inputs.feedback1 }}
            • Pair 2 ⇒ ${{ inputs.feedback2 }}
            • Pair 3 ⇒ ${{ inputs.feedback3 }}

            (Workflow run → https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
