name: Submit Feedback as GitHub Issue

on:
  workflow_dispatch:  # Allow manually triggering the workflow

jobs:
  submit-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Issue for Feedback
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "Video Feedback Submission", "body": "Feedback 1: ${feedback1}\nFeedback 2: ${feedback2}\nFeedback 3: ${feedback3}"}' \
            https://api.github.com/repos/${{ secrets.OWNER }}/${{ secrets.REPO }}/issues
        env:
          feedback1: ${{ secrets.FEEDBACK1 }}
          feedback2: ${{ secrets.FEEDBACK2 }}
          feedback3: ${{ secrets.FEEDBACK3 }}
