name: Send video-feedback email

on:
  workflow_dispatch:
    inputs:
      name:
        description: Participant name
        required: true
        type: string
      affiliation:
        description: Affiliation
        required: true
        type: string
      position:
        description: Job title / position
        required: true
        type: string
      feedback1:
        description: Preferred video for pair 1
        required: true
        type: string
      feedback2:
        description: Preferred video for pair 2
        required: true
        type: string
      feedback3:
        description: Preferred video for pair 3
        required: true
        type: string

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send feedback mail
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "New TacTGen Feedback Received"
          to:     "820144073@qq.com"
          from:   "TacTGen Bot <${{ secrets.MAIL_USERNAME }}>"
          body: |
            A visitor has submitted the feedback as follows:

            Participant: **${{ inputs.name }}**
            Affiliation: ${{ inputs.affiliation }}
            Position:    ${{ inputs.position }}

            • Pair 1 ⇒ ${{ inputs.feedback1 }}
            • Pair 2 ⇒ ${{ inputs.feedback2 }}
            • Pair 3 ⇒ ${{ inputs.feedback3 }}

            (Workflow run → https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
