name: Send video-feedback email

on:
  workflow_dispatch:
    inputs:
      name:        {description: Participant name,         required: true, type: string}
      affiliation: {description: Affiliation,              required: true, type: string}
      position:    {description: Job title / position,     required: true, type: string}
      responses:   {description: 'JSON map videoID→answer',required: true, type: string}

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get -y update && sudo apt-get -y install jq

      - name: Format mail body
        id: fmt
        run: |
          {
            printf 'A visitor has submitted the feedback as follows:\n\n'
            printf 'Participant: %s\n'  "${{ inputs.name }}"
            printf 'Affiliation: %s\n'  "${{ inputs.affiliation }}"
            printf 'Position:    %s\n\n' "${{ inputs.position }}"

            echo '${{ inputs.responses }}' \
              | jq -r 'to_entries[] | "• \(.key) ⇒ \(.value)"'

            printf '\n(Workflow run → https://github.com/%s/actions/runs/%s)\n' \
                   "${{ github.repository }}" "${{ github.run_id }}"
          } >mail.txt

          echo 'body<<EOF'   >>"$GITHUB_OUTPUT"
          cat  mail.txt      >>"$GITHUB_OUTPUT"
          echo 'EOF'         >>"$GITHUB_OUTPUT"

      - name: Send feedback mail
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject:  "New TacTGen Feedback Received"
          to:       "820144073@qq.com"
          from:     "TacTGen Bot <${{ secrets.MAIL_USERNAME }}>"
          body:     ${{ steps.fmt.outputs.body }}
